# Generated by Django 5.1.1 on 2024-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
