from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('registrarse/', registrarse, name="registrarse"),
    path('registro_usuario/', register_user, name="registro_usuario"),
    path('login/', login_view, name="login"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),
    path('crear_receta/', create_recipe, name="crear_receta"),
    path('ver_receta_propia/', ver_recetas_propias, name="ver_receta_propia"),
    path('receta/<int:recipe_id>/', recipe_detail, name='recipe_detail'),
    path('receta/editar/<int:recipe_id>/', edit_recipe, name='edit_recipe'),
    path('receta/eliminar/<int:recipe_id>/', delete_recipe, name='delete_recipe'),
    path('recipe/<int:recipe_id>/rate/', rate_recipe, name='rate_recipe'),
    path('recipe/<int:recipe_id>/comment/', add_comment, name='add_comment'),
    path('recipes/', all_recipes, name='all_recipes'),
    path('collections/new/', create_collection, name='create_collection'),
    path('add-recipe-to-collections/<int:recipe_id>', add_recipe_to_collections, name='add_recipe_to_collections'),
    path('colecciones/', user_collections, name='user_collections'),
    path('colecciones/<int:collection_id>/', collection_detail, name='collection_detail'),
    path('colecciones/eliminar/<int:collection_id>/', collection_delete, name='collection_delete'),
    path('profile', edit_profile, name="edit_profile"),
    path('profile/siguiendo', following_list, name="following_list"),
    path('profile/seguidos', followers_list, name="followers_list"),
    path('follow/<int:user_id>/<int:recipe_id>/', follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', unfollow_user, name='unfollow_user'),
    path('recuperar_contraseña/', recuperar_contraseña, name='recuperar_contraseña'),
    path('validar_codigo/', validar_codigo, name='validar_codigo'),
    path('cambio_contraseña/', cambio_contraseña, name='cambio_contraseña'),
]